package cn.itcast.entity;
// Generated 2017-6-14 22:08:02 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Classcourse generated by hbm2java
 */
@Entity
@Table(name = "classcourse", catalog = "coursesystem")
public class Classcourse implements java.io.Serializable {

	private Integer id;
	private Course course;
	private String coursertime;
	private String courseaddr;
	private String classname;
	private String coursedata;

	public Classcourse() {
	}

	public Classcourse(Course course, String coursertime, String courseaddr, String classname) {
		this.course = course;
		this.coursertime = coursertime;
		this.courseaddr = courseaddr;
		this.classname = classname;
	}

	public Classcourse(Course course, String coursertime, String courseaddr, String classname, String coursedata) {
		this.course = course;
		this.coursertime = coursertime;
		this.courseaddr = courseaddr;
		this.classname = classname;
		this.coursedata = coursedata;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cno", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "coursertime", nullable = false, length = 20)
	public String getCoursertime() {
		return this.coursertime;
	}

	public void setCoursertime(String coursertime) {
		this.coursertime = coursertime;
	}

	@Column(name = "courseaddr", nullable = false, length = 20)
	public String getCourseaddr() {
		return this.courseaddr;
	}

	public void setCourseaddr(String courseaddr) {
		this.courseaddr = courseaddr;
	}

	@Column(name = "classname", nullable = false, length = 20)
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	@Column(name = "coursedata", length = 20)
	public String getCoursedata() {
		return this.coursedata;
	}

	public void setCoursedata(String coursedata) {
		this.coursedata = coursedata;
	}

}
