package cn.itcast.entity;
// Generated 2017-6-16 9:48:00 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Class1 generated by hbm2java
 */
@Entity
@Table(name = "class1", catalog = "coursesystem")
public class Class1 implements java.io.Serializable {

	private Integer classid;
	private String classname;
	private Set<Stuclas> stuclases = new HashSet<Stuclas>(0);

	public Class1() {
	}

	public Class1(String classname, Set<Stuclas> stuclases) {
		this.classname = classname;
		this.stuclases = stuclases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "classid", unique = true, nullable = false)
	public Integer getClassid() {
		return this.classid;
	}

	public void setClassid(Integer classid) {
		this.classid = classid;
	}

	@Column(name = "classname", length = 20)
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "class1")
	public Set<Stuclas> getStuclases() {
		return this.stuclases;
	}

	public void setStuclases(Set<Stuclas> stuclases) {
		this.stuclases = stuclases;
	}

}
