package cn.itcast.entity;
// Generated 2017-6-14 22:08:02 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Class generated by hbm2java
 */
@Entity
@Table(name = "class", catalog = "coursesystem")
public class Class implements java.io.Serializable {

	private Integer classid;
	private String classname;

	public Class() {
	}

	public Class(String classname) {
		this.classname = classname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "classid", unique = true, nullable = false)
	public Integer getClassid() {
		return this.classid;
	}

	public void setClassid(Integer classid) {
		this.classid = classid;
	}

	@Column(name = "classname", length = 20)
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

}
