package cn.itcast.entity;
// Generated 2017-6-16 9:48:00 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "coursesystem")
public class Course implements java.io.Serializable {

	private int cno;
	private String cname;
	private Set<Classcourse> classcourses = new HashSet<Classcourse>(0);
	private Set<Tc> tcs = new HashSet<Tc>(0);

	public Course() {
	}

	public Course(int cno) {
		this.cno = cno;
	}

	public Course(int cno, String cname, Set<Classcourse> classcourses, Set<Tc> tcs) {
		this.cno = cno;
		this.cname = cname;
		this.classcourses = classcourses;
		this.tcs = tcs;
	}

	@Id

	@Column(name = "cno", unique = true, nullable = false)
	public int getCno() {
		return this.cno;
	}

	public void setCno(int cno) {
		this.cno = cno;
	}

	@Column(name = "cname", length = 20)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Classcourse> getClasscourses() {
		return this.classcourses;
	}

	public void setClasscourses(Set<Classcourse> classcourses) {
		this.classcourses = classcourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Tc> getTcs() {
		return this.tcs;
	}

	public void setTcs(Set<Tc> tcs) {
		this.tcs = tcs;
	}

}
