package cn.itcast.entity;
// Generated 2017-6-14 22:08:02 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "coursesystem")
public class Course implements java.io.Serializable {

	private int cno;
	private String cname;
	private String tname;
	private Set<Classcourse> classcourses = new HashSet<Classcourse>(0);

	public Course() {
	}

	public Course(int cno) {
		this.cno = cno;
	}

	public Course(int cno, String cname, String tname, Set<Classcourse> classcourses) {
		this.cno = cno;
		this.cname = cname;
		this.tname = tname;
		this.classcourses = classcourses;
	}

	@Id

	@Column(name = "cno", unique = true, nullable = false)
	public int getCno() {
		return this.cno;
	}

	public void setCno(int cno) {
		this.cno = cno;
	}

	@Column(name = "cname", length = 20)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "tname", length = 20)
	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Classcourse> getClasscourses() {
		return this.classcourses;
	}

	public void setClasscourses(Set<Classcourse> classcourses) {
		this.classcourses = classcourses;
	}

}
