package cn.itcast.entity;
// Generated 2017-6-14 22:08:02 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StuclasId generated by hbm2java
 */
@Embeddable
public class StuclasId implements java.io.Serializable {

	private int sno;
	private int classid;

	public StuclasId() {
	}

	public StuclasId(int sno, int classid) {
		this.sno = sno;
		this.classid = classid;
	}

	@Column(name = "sno", nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "classid", nullable = false)
	public int getClassid() {
		return this.classid;
	}

	public void setClassid(int classid) {
		this.classid = classid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StuclasId))
			return false;
		StuclasId castOther = (StuclasId) other;

		return (this.getSno() == castOther.getSno()) && (this.getClassid() == castOther.getClassid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSno();
		result = 37 * result + this.getClassid();
		return result;
	}

}
