package cn.itcast.entity;
// Generated 2017-6-14 22:08:02 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Stuclas generated by hbm2java
 */
@Entity
@Table(name = "stuclas", catalog = "coursesystem")
public class Stuclas implements java.io.Serializable {

	private StuclasId id;

	public Stuclas() {
	}

	public Stuclas(StuclasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "sno", column = @Column(name = "sno", nullable = false)),
			@AttributeOverride(name = "classid", column = @Column(name = "classid", nullable = false)) })
	public StuclasId getId() {
		return this.id;
	}

	public void setId(StuclasId id) {
		this.id = id;
	}

}
