package cn.itcast.entity;
// Generated 2017-6-14 22:08:02 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "coursesystem")
public class Student implements java.io.Serializable {

	private int sno;
	private String sname;
	private String spassword;
	private String sclass;
	private String ssex;

	public Student() {
	}

	public Student(int sno, String sname) {
		this.sno = sno;
		this.sname = sname;
	}

	public Student(int sno, String sname, String spassword, String sclass, String ssex) {
		this.sno = sno;
		this.sname = sname;
		this.spassword = spassword;
		this.sclass = sclass;
		this.ssex = ssex;
	}

	@Id

	@Column(name = "sno", unique = true, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "sname", nullable = false, length = 20)
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	@Column(name = "spassword", length = 20)
	public String getSpassword() {
		return this.spassword;
	}

	public void setSpassword(String spassword) {
		this.spassword = spassword;
	}

	@Column(name = "sclass", length = 20)
	public String getSclass() {
		return this.sclass;
	}

	public void setSclass(String sclass) {
		this.sclass = sclass;
	}

	@Column(name = "ssex", length = 4)
	public String getSsex() {
		return this.ssex;
	}

	public void setSsex(String ssex) {
		this.ssex = ssex;
	}

}
