package cn.itcast.entity;
// Generated 2017-6-14 22:08:02 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tc generated by hbm2java
 */
@Entity
@Table(name = "tc", catalog = "coursesystem")
public class Tc implements java.io.Serializable {

	private TcId id;

	public Tc() {
	}

	public Tc(TcId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cno", column = @Column(name = "cno", nullable = false)),
			@AttributeOverride(name = "tname", column = @Column(name = "tname", nullable = false, length = 20)) })
	public TcId getId() {
		return this.id;
	}

	public void setId(TcId id) {
		this.id = id;
	}

}
