package cn.itcast.entity;
// Generated 2017-6-14 22:08:02 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TcId generated by hbm2java
 */
@Embeddable
public class TcId implements java.io.Serializable {

	private int cno;
	private String tname;

	public TcId() {
	}

	public TcId(int cno, String tname) {
		this.cno = cno;
		this.tname = tname;
	}

	@Column(name = "cno", nullable = false)
	public int getCno() {
		return this.cno;
	}

	public void setCno(int cno) {
		this.cno = cno;
	}

	@Column(name = "tname", nullable = false, length = 20)
	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TcId))
			return false;
		TcId castOther = (TcId) other;

		return (this.getCno() == castOther.getCno())
				&& ((this.getTname() == castOther.getTname()) || (this.getTname() != null
						&& castOther.getTname() != null && this.getTname().equals(castOther.getTname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCno();
		result = 37 * result + (getTname() == null ? 0 : this.getTname().hashCode());
		return result;
	}

}
