package cn.itcast.entity;
// Generated 2017-6-16 9:48:00 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "coursesystem")
public class Teacher implements java.io.Serializable {

	private Integer tnumber;
	private String tname;
	private String tpassword;
	private Set<Tc> tcs = new HashSet<Tc>(0);

	public Teacher() {
	}

	public Teacher(String tname, String tpassword, Set<Tc> tcs) {
		this.tname = tname;
		this.tpassword = tpassword;
		this.tcs = tcs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tnumber", unique = true, nullable = false)
	public Integer getTnumber() {
		return this.tnumber;
	}

	public void setTnumber(Integer tnumber) {
		this.tnumber = tnumber;
	}

	@Column(name = "tname", length = 20)
	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	@Column(name = "tpassword", length = 20)
	public String getTpassword() {
		return this.tpassword;
	}

	public void setTpassword(String tpassword) {
		this.tpassword = tpassword;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "teacher")
	public Set<Tc> getTcs() {
		return this.tcs;
	}

	public void setTcs(Set<Tc> tcs) {
		this.tcs = tcs;
	}

}
